title: Yu Wang
url: "https://zedrover.github.io"
baseurl: "/"
local_theme: researcher
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Powered by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "cv2024.pdf"
 - name: "Contact"
   link: "contact"
